# ==============================================================================
# MIA Setup Script
# Run this script once to install dependencies and configure your environment.
# ==============================================================================

Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║        🤖 MIA INITIAL SETUP            ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# 1. Check Python
Write-Host "[1/4] Checking Python..." -ForegroundColor Yellow
$pythonCheck = Get-Command "python" -ErrorAction SilentlyContinue
if ($null -eq $pythonCheck) {
    Write-Host "❌ Python is not installed or not in PATH. Please install Python 3.10+ first." -ForegroundColor Red
    exit 1
}
Write-Host "✅ Python found." -ForegroundColor Green

# 2. Install Dependencies
Write-Host "`n[2/4] Installing dependencies..." -ForegroundColor Yellow
$repoRoot = (Get-Item -Path ".\").FullName
$reqPath = Join-Path $repoRoot "server\requirements.txt"
if (Test-Path $reqPath) {
    python -m pip install -r $reqPath
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Failed to install dependencies." -ForegroundColor Red
        exit 1
    }
    Write-Host "✅ Dependencies installed." -ForegroundColor Green
} else {
    Write-Host "❌ requirements.txt not found at $reqPath" -ForegroundColor Red
    exit 1
}

# 3. Generate Secret
Write-Host "`n[3/4] Generating secrets..." -ForegroundColor Yellow
$jwtSecret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 64 | % {[char]$_})
Write-Host "✅ Secrets generated." -ForegroundColor Green

# 4. Interactive Configuration
Write-Host "`n[4/4] Configuration" -ForegroundColor Yellow
$envPath = Join-Path $repoRoot ".env"

if (Test-Path $envPath) {
    $overwrite = Read-Host "⚠️ .env file already exists. Overwrite? (y/n)"
    if ($overwrite.ToLower() -ne 'y') {
        Write-Host "Setup aborted."
        exit 0
    }
}

Write-Host "`nSelect AI Provider:"
Write-Host "1. Google Gemini (Free Tier Available - Recommended)"
Write-Host "2. OpenAI"
Write-Host "3. Ollama (Local)"
$providerChoice = Read-Host "Enter choice (1/2/3) [Default: 1]"

$provider = "gemini"
$geminiKey = ""
$openaiKey = ""
$ollamaUrl = "http://localhost:11434"
$ollamaModel = "llama3"

if ($providerChoice -eq "2") {
    $provider = "openai"
    $openaiKey = Read-Host "Enter OpenAI API Key"
} elseif ($providerChoice -eq "3") {
    $provider = "ollama"
    $ollamaUrl = Read-Host "Enter Ollama Base URL [Default: $ollamaUrl]"
    if ([string]::IsNullOrWhiteSpace($ollamaUrl)) { $ollamaUrl = "http://localhost:11434" }
    $ollamaModel = Read-Host "Enter Ollama Model [Default: $ollamaModel]"
    if ([string]::IsNullOrWhiteSpace($ollamaModel)) { $ollamaModel = "llama3" }
} else {
    $provider = "gemini"
    Write-Host "Get your free API key at: https://aistudio.google.com/" -ForegroundColor Cyan
    $geminiKey = Read-Host "Enter Gemini API Key"
}

$password = Read-Host -AsSecureString "Enter a secure login password for MIA"
$bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($password)
$plainPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)

# Write to .env
$envContent = @"
# ============================================
# MIA — Configuration
# Generated by setup.ps1
# ============================================

# --- AI Model Configuration ---
AI_PROVIDER=$provider
GEMINI_API_KEY=$geminiKey
OPENAI_API_KEY=$openaiKey
OLLAMA_BASE_URL=$ollamaUrl
OLLAMA_MODEL=$ollamaModel

# --- Security ---
MIA_PASSWORD=$plainPassword
JWT_SECRET=$jwtSecret
SESSION_EXPIRY_HOURS=24

# --- Server ---
HOST=0.0.0.0
PORT=8765

# --- Screen Streaming ---
SCREEN_FPS=30
SCREEN_QUALITY=50
SCREEN_AUTO_RESOLUTION=true

# --- Cloudflare Tunnel ---
TUNNEL_HOSTNAME=
"@

Set-Content -Path $envPath -Value $envContent
Write-Host "`n✅ Setup Complete! .env file generated." -ForegroundColor Green
Write-Host "You can now run '.\scripts\start.ps1' to launch MIA." -ForegroundColor Cyan
Write-Host ""
